#!/bin/bash

yarn workspace @redhatinsights/backstage-plugin-progressive-delivery-frontend export-dynamic
cd plugins/progressive-delivery-frontend
rm *.tgz
npm pack ./dist-dynamic
cd ../..
mv plugins/progressive-delivery-frontend/*.tgz .
sha256sum *.tgz | awk '{print $1}' | xxd -r -p | base64
